export const [LOGIN, REGISTER, LOGOUT] = ['LOGIN', 'REGISTER', 'LOGOUT'];
export const [UPLOAD_IMAGE, UPLOAD_USERINFO] = ['UPLOAD_IMAGE', 'UPLOAD_USERINFO'];
export const [GET_USERINFO] = ['GET_USERINFO'];
