export const [LOGIN, LOGOUT] = ['LOGIN', 'LOGOUT'];
export const [UPLOAD_IMAGE, UPLOAD_USERINFO] = ['UPLOAD_IMAGE', 'UPLOAD_USERINFO'];
export const GET_USERINFO = 'GET_USERINFO';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
