const make = TYPE => [TYPE, `${TYPE}_SUCCESS`, `${TYPE}_FAIL`];

export const [LOGIN, LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT] = ['LOGIN', 'LOGIN_SUCCESS', 'LOGIN_FAIL', 'LOGOUT'];
export const [REGISTER, REGISTER_SUCCESS, REGISTER_FAIL] = ['REGISTER', 'REGISTER_SUCCESS', 'REGISTER_FAIL'];
export const [UPLOAD_IMAGE, UPLOAD_IMAGE_SUCCESS, UPLOAD_IMAGE_FAIL] = make('UPLOAD_IMAGE');
